export const getThemeStyles = (theme, metadata) => {
  switch (theme) {
    case 'dark':
      return {
        backgroundGradient: {
          start: metadata.backgroundGradientDark.start,
          end: metadata.backgroundGradientDark.end,
        },
        color_map_icons: '#ffffff',
        color_map_icons_container: '#22272E',
        color_map_list_view_border: '#424d5b',
        color_map_list_view_background: '#22272E',
        color_map_list_view_text: '#D9D9D9',
        iconColor: '#D3D3D3',
        color: '#D3D3D3',
        authPage: {
          titleTextColor: '#e0e0e0',
          cardBackgroundColor: '#22272E',
          welcomeTextColor: '#e0e0e0',
          tabHeaderBackgroundColor: '#15191C',
          activeTabButtonColor: '#12A88C',
          tabTextColor: '#e0e0e0',
          activeTabTextColor: '#FFFFFF',
          loginForm: {
            labelTextColor: '#E3E5E6',
            inputBorderColor: '#393E46',
            inputTextColor: '#E3E5E6',
            passwordIconColor: '#d5d5d5',
            placeholderTextColor: '#707070',
            passwordInputTextColor: '#E3E5E6',
            rememberTextColor: '#C8C8CA',
            forgotTextColor: '#FF6B6B',

            loginButtonBackgroundColor: '#12A88C',
            loginButtonTextColor: '#FFFFFF',

            dividerLineColor: '#393E46',
            dividerTextColor: '#A0A0A2',

            socialButtonBackgroundColor: '#2C2F36',
            socialFacebookColor: '#1877F2',
            socialGoogleColor: '#db4437',
            socialAppleColor: '#FFFFFF',

            bottomTextColor: '#A0A0A2',
            signUpLinkColor: '#D34445',
          },
          signUpForm: {
            labelTextColor: '#E3E5E6',
            inputBorderColor: '#393E46',
            inputTextColor: '#E3E5E6',
            inputBackgroundColor: '#22272E',
            passwordContainerBorderColor: '#393E46',
            passwordContainerBackgroundColor: '#22272E',
            passwordInputTextColor: '#E3E5E6',
            placeholderTextColor: '#707070',
            passwordIconColor: '#d5d5d5',
            rememberTextColor: '#C8C8CA',

            loginButtonBackgroundColor: '#12A88C',
            loginButtonTextColor: '#FFFFFF',
          },
        },
        forgetPassword: {
          back_button_background_color: '#14b8a518',
          back_button_icon_color: '#E3E5E6',
          input_placeholder_color: '#9CA3AF',
          input_color: '#E3E5E6',
          header_color: '#E3E5E6',
          sub_header_color: '#9CA3AF',
          label_color: '#E3E5E6',
          input_border_color: '#14b8a518',
          input_background_color: '#14b8a518',
          continue_button_background_color: '#12A88C',
          continue_button_text_color: '#ffffff',
          resetPassword_eye_close_icon_color: '#606060',
          resetPassword_eye_open_icon_color: '#828282',
        },
        modalStyles: {
          headerColor: '#F9FAFB',
          subHeaderColor: '#D1D5DB',
          bodyColor: '#E5E7EB',
          listBulletColor: '#E5E7EB',
          linkColor: '#3B82F6',
          backgroundColor: '#22272E',
          closeBtnColor: '#12A88C',
        },
        bottomBar: {
          backgroundColor: '#292F37',
          color: '#B9B9B9',
          button_color: '#0B715E',
          button_icon_color: '#F6F4EA',
          button_outer_ring: '#12A88C',
          selected_color: '#0F8972',
        },
        grievanceSlider: {
          backgroundColor_card: '#1d2229',
          color_text: '#D3D3D3',
          color_icon: '#ffffff',
        },
        topNavbar: {
          backgroundColor: '#15191C',
          color: '#D3D3D3',
          icon_color: '#D3D3D3',
          badge_color: '#D34445',
        },
        subNavbar: {
          color: '#9C9C9A',
        },
        settings: {
          backgroundColor_card: '#22272E',
          color_text: '#D3D3D3',
          color_icon: '#D3D3D3',
          toggle_button_on: '#A8A8A8',
          toggle_button_off: '#D3D3D3',

          language_border_color: '#3641535e',
          language_active_background_color: '#3641535e',
          language_radio_border_color: '#364153',
          language_radio_active_background_color: '#A8A8A8',
        },
        helpCenter: {
          card_background: '#22272E',
          content_background: '#252525',
          title_color: '#D3D3D3',
          subheading_color: '#CCCCCC',
          paragraph_color: '#BBBBBB',
          list_color: '#AAAAAA',
          icon_color: '#FFFFFF',
        },
        privacyPolicy: {
          background_section: '#121314',
          color_heading: '#38bdf8',
          color_subheading: '#ffffff',
          color_paragraph: '#d1d5db',
          color_paragraph_muted: '#9ca3af',
          border_color: '#374151',
          color_icon: '#38bdf8',
          color_list: '#d1d5db',
        },
        about: {
          background_section: '#121314',
          color_heading: '#38bdf8',
          color_subheading: '#ffffff',
          color_paragraph: '#d1d5db',
          color_paragraph_muted: '#9ca3af',
          color_list: '#d1d5db',
          border_color: '#374151',
        },
        termsAndConditions: {
          background_main: '#1a1d1f',
          background_section: '#121314',
          color_heading: '#38bdf8',
          color_subheading: '#ffffff',
          color_paragraph: '#d1d5db',
          color_paragraph_muted: '#9ca3af',
          color_list: '#d1d5db',
          border_color: '#374151',
        },
        editProfile: {
          color_label: '#e0e0e0',
          color_border: '#333a44',
          color_header: '#e0e0e0',
          placeholderColor: '#707070',
          color_button_text: '#FFFFFF',
          color_button: '#D34445',
          color_icon: '#FFFFFF',
          color_icon_container: '#4CAF50',
          color_validation: '#EA4335',
          color_text: '#D3D3D3',
          color_title: '#F8FCFF',
          avatar_ring: '#D34445',
          cardBackgroundGradient: {
            start: '#191d21',
            end: '#15191C',
          },
          input_background: '#22272E',
          avatarCardBackgroundGradient: {
            start: '#15191C',
            end: '#191d21',
          },
          gradientAngle: {
            start: { x: 1, y: 0 },
            end: { x: 0, y: 1 },
          },
          slider: {
            backgroundColor_card: '#1d2229',
            slider_header_color: '#e0e0e0',
            camera_container_background: '#22272E',
            camera_text_icon_color: '#96c7ff',
            gallery_container_background: '#00413b',
            gallery_text_icon_color: '#e0e0e0',
            handlebar_color: '#5b5b5b',
          },
        },
        home: {
          separator_color: '#0b9f8485',
          title_color: '#1DE9B6',
          name_color: '#e2e2e2',
          description_color: '#B0BEC5',
        },
        document: {
          backgroundColor_card: '#22272E',
          color_text: '#D3D3D3',
          color_subtext: '#0D997E',
          color_icon: '#D3D3D3',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],
        },
        payment: {
          backgroundColor_card: '#22272E',
          color_text: '#D3D3D3',
          color_subtext: '#0D997E',
          color_icon: '#D3D3D3',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],
        },
        notification: {
          backgroundColor_card: '#22272E',
          color_text: '#D3D3D3',
          color_subtext: '#0D997E',
          color_icon: '#9c9c9c',
          color_icon_left: '#FFFFFF',
          icon_container: '#074236',
        },
        applicationStatus: {
          backgroundColor_card: '#22272E',
          color_text: '#D3D3D3',
          color_subtext: '#0D997E',
          color_icon: '#D3D3D3',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],

          color_stepper_date: '#0D997E',
          color_stepper_title: '#D3D3D3',
          color_stepper_description: '#0A6D5A',
          color_stepper_completed: '#5678FF',
          color_stepper_inProgress: '#FFC734',
          color_stepper_notStarted: '#BDBDBD',
        },
        profile: {
          color_text: '#D3D3D3',
          color_title: '#F8FCFF',
          color_logout: '#E53935',
          color_icon: '#D3D3D3',
          avatar_ring: '#D34445',
          backgroundGradient: {
            start: '#22272E',
            end: '#15191C',
          },
          backgroundColor_card: '#22272E',
          edit_button: {
            backgroundColor: '#ffffffe0',
            icon_color: '#7098EF',
          },
        },
        sliderScreen: {
          backgroundColor: '#15191C',
          input_background: '#22272E',
          color_header: '#e0e0e0',
          color_label: '#e0e0e0',
          color_icon: '#FFFFFF',
          color_icon_container: '#4CAF50',
          color_border: '#333a44',
          color_button: '#D34445',
          color_button_text: '#FFFFFF',
          color_validation: '#EA4335',
          backgroundColor_upload: '#22272E',
          placeholderColor: '#707070',
          color_slider_icon: '#707070',

          upload_image_modal_background: '#22272E',
          upload_image_icon_color: '#96c7ff',
          upload_image_icon_container: '#303742',
          upload_image_header_color: '#e0e0e0',
          upload_image_info_color: '#b0b0b0',
          camera_container_background: '#007E74',
          camera_text_icon_color: '#e0e0e0',
          gallery_container_background: '#364153',
          divider_color: '#3c414c',
          divider_text_color: '#9a9a9a',
          gallery_text_icon_color: '#e0e0e0',
          cancel_button_background: '#232830',
          cancel_button_border_color: '#364153',
          cancel_button_text_color: '#e0e0e0',
        },
      };
    case 'light':
      return {
        backgroundGradient: {
          start: metadata.backgroundGradient.start,
          end: metadata.backgroundGradient.end,
        },
        color_map_icons: '#186EDF',
        color_map_icons_container: '#ffffff',
        color_map_list_view_border: '#eee',
        color_map_list_view_background: '#fff',
        color_map_list_view_text: '#0A6D5A',
        iconColor: '#075949',
        color: '#075949',
        authPage: {
          titleTextColor: '#075949',
          cardBackgroundColor: '#FFFFFF',
          welcomeTextColor: '#0A6D5A',
          tabHeaderBackgroundColor: '#F9F8F6',
          activeTabButtonColor: '#f57c00',
          tabTextColor: '#075949',
          activeTabTextColor: '#FFFFFF',
          loginForm: {
            labelTextColor: '#7F7F81',
            inputBorderColor: '#EEF9F7',
            inputTextColor: '#888888',
            passwordIconColor: '#22272E',

            passwordInputTextColor: '#7F7F81',
            rememberTextColor: '#808082',
            forgotTextColor: '#BD6D62',

            loginButtonBackgroundColor: '#f57c00',
            loginButtonTextColor: '#FFFFFF',

            dividerLineColor: '#E8F5F2',
            dividerTextColor: '#C8C8CA',

            socialButtonBackgroundColor: '#f0f0f0',
            socialFacebookColor: '#3b5998',
            socialGoogleColor: '#db4437',
            socialAppleColor: '#000000',

            bottomTextColor: '#C8C8CA',
            signUpLinkColor: '#f57c00',
          },
          signUpForm: {
            labelColor: '#7F7F81',
            inputBorderColor: '#EEF9F7',
            inputTextColor: '#888888',
            inputBackgroundColor: '#ffffff',
            passwordContainerBorderColor: '#EEF9F7',
            passwordInputTextColor: '#7F7F81',
            passwordContainerBackgroundColor: '#fff',
            passwordInputColor: '#7F7F81',
            passwordIconColor: '#22272E',
            rememberTextColor: '#808082',
            loginButtonBackgroundColor: '#f57c00',
            loginButtonTextColor: '#fff',
            placeholderTextColor: '#999',
            iconColor: '#E3E3E3',
          },
        },
        forgetPassword: {
          back_button_background_color: '#ffffff7b',
          back_button_icon_color: '#075949',
          input_placeholder_color: '#9CA3AF',
          input_color: '#075949',
          header_color: '#075949',
          sub_header_color: '#444',
          label_color: '#7F7F81',
          input_border_color: '#14b8a518',
          input_background_color: '#fff',
          continue_button_background_color: '#FF8B2C',
          continue_button_text_color: '#ffffff',
          resetPassword_eye_close_icon_color: '#d2d2d2',
          resetPassword_eye_open_icon_color: '#888888',
        },
        modalStyles: {
          headerColor: '#7F7F81',
          subHeaderColor: '#888888',
          bodyColor: '#1C1C1C',
          listBulletColor: '#1C1C1C',
          linkColor: '#007AFF',
          backgroundColor: '#ffffff',
          closeBtnColor: '#f57c00',
        },
        bottomBar: {
          backgroundColor: 'white',
          color: '#075949',
          button_color: '#FF8B2C',
          button_icon_color: '#F6F4EA',
          button_outer_ring: '#F6F4EA',
          selected_color: '#1C6758',
        },
        grievanceSlider: {
          backgroundColor_card: '#f8f8f8',
          color_text: '#075949',
          color_icon: '#ffffff',
        },
        topNavbar: {
          backgroundColor: 'transparent',
          color: '#333333',
          icon_color: '#12A88C',
          badge_color: '#D34445',
        },
        subNavbar: {
          color: '#1C6758',
        },
        settings: {
          backgroundColor_card: '#FFFFFF',
          color_text: '#075949',
          color_icon: '#075949',
          toggle_button_on: '#A8A8A8',
          toggle_button_off: '#D3D3D3',

          language_border_color: '#3641530e',
          language_active_background_color: '#3641530e',
          language_radio_border_color: '#0759499f',
          language_radio_active_background_color: '#075949',
        },
        helpCenter: {
          card_background: '#FFFFFF',
          content_background: '#FAFAFA',
          title_color: '#075949',
          subheading_color: '#2E2E2E',
          paragraph_color: '#444',
          list_color: '#333',
          icon_color: '#555',
        },

        privacyPolicy: {
          background_section: '#ffffff',
          color_heading: '#047857',
          color_subheading: '#065f46',
          color_paragraph: '#374151',
          color_paragraph_muted: '#4b5563',
          border_color: '#e5e7eb',
          color_icon: '#047857',
          color_list: '#374151',
        },
        about: {
          background_main: '#f5f3ed',
          background_section: '#ffffff',
          color_heading: '#047857',
          color_subheading: '#065f46',
          color_paragraph: '#374151',
          color_paragraph_muted: '#4b5563',
          color_list: '#374151',
          border_color: '#e5e7eb',
        },
        termsAndConditions: {
          background_main: '#f5f3ed', // light mode
          background_section: '#ffffff',
          color_heading: '#047857',
          color_subheading: '#065f46',
          color_paragraph: '#374151',
          color_paragraph_muted: '#4b5563',
          color_list: '#374151',
          border_color: '#e5e7eb',
        },
        editProfile: {
          color_label: '#686868',
          color_border: '#D3D3D3',
          color_header: '#828282',
          placeholderColor: '#828282',
          color_button_text: '#FFFFFF',
          color_button: '#12A88C',
          color_icon: '#FFFFFF',
          color_icon_container: '#4CAF50',
          color_validation: '#EA4335',
          color_text: '#D3D3D3',
          color_title: '#F8FCFF',
          avatar_ring: '#FF8C42',
          cardBackgroundGradient: {
            start: '#FFFFFF',
            end: '#FFFFFF',
          },
          avatarCardBackgroundGradient: {
            start: '#FFF7EC',
            end: '#ffffff',
          },
          gradientAngle: {
            start: { x: 0, y: 0 },
            end: { x: 0, y: 1 },
          },
          slider: {
            backgroundColor_card: '#FFFFFF',
            slider_header_color: '#828282',
            camera_container_background: '#E0F0FF',
            camera_text_icon_color: '#007AFF',
            gallery_container_background: '#E6F9F2',
            gallery_text_icon_color: '#12A88C',
            handlebar_color: '#cccccc',
          },
        },
        home: {
          separator_color: '#b27a016c',
          title_color: '#00796B',
          name_color: '#333',
          description_color: '#555',
        },
        document: {
          backgroundColor_card: '#FFFFFF',
          color_text: '#0A6D5A',
          color_subtext: '#0D997E',
          color_icon: '#0A6D5A',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],
        },
        payment: {
          backgroundColor_card: '#FFFFFF',
          color_text: '#0A6D5A',
          color_subtext: '#0D997E',
          color_icon: '#0A6D5A',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],
        },
        notification: {
          backgroundColor_card: '#FFFFFF',
          color_text: '#0A6D5A',
          color_subtext: '#0D997E',
          color_icon: '#0A6D5A',
          color_icon_left: '#FFFFFF',
          icon_container: '#dcfce7',
        },
        applicationStatus: {
          backgroundColor_card: '#FFFFFF',
          color_text: '#0A6D5A',
          color_subtext: '#0D997E',
          color_icon: '#0A6D5A',
          color_icon_left: '#FFFFFF',
          color_icon_container: ['#5678FF', '#FFC734'],

          color_stepper_date: '#0A6D5A',
          color_stepper_title: '#0A6D5A',
          color_stepper_description: '#0A6D5A',
          color_stepper_completed: '#5678FF',
          color_stepper_inProgress: '#FFC734',
          color_stepper_notStarted: '#BDBDBD',
        },
        profile: {
          color_text: '#075949',
          color_title: '#636363',
          color_icon: '#075949',
          color_logout: '#E53935',
          avatar_ring: '#FF8C42',
          backgroundGradient: {
            start: '#FFF7EC',
            end: '#FFE5C2',
          },
          backgroundColor_card: '#FFFFFF',
          edit_button: {
            backgroundColor: '#ffffffdf',
            icon_color: '#FF8C42',
          },
        },
        sliderScreen: {
          backgroundColor: '#FFFFFF',
          input_background: '#FFFFFF',
          color_header: '#09876F',
          color_label: '#8a8a8a',
          color_icon: '#FFFFFF',
          color_icon_container: '#4CAF50',
          color_border: '#D3D3D3',
          color_button: '#12A88C',
          color_button_text: '#FFFFFF',
          color_validation: '#EA4335',
          backgroundColor_upload: '#d3d3d351',
          placeholderColor: '#D9D9D9',
          color_slider_icon: '#D3D3D3',

          upload_image_modal_background: '#FFFFFF',
          upload_image_icon_color: '#007AFF',
          upload_image_icon_container: '#E0F0FF',
          upload_image_header_color: '#636363',
          upload_image_info_color: '#b0b0b0',
          camera_container_background: '#E0F0FF',
          camera_text_icon_color: '#007AFF',
          divider_color: '#d4e5df',
          divider_text_color: '#9a9a9a',
          gallery_container_background: '#E6F9F2',
          gallery_text_icon_color: '#12A88C',
          cancel_button_background: '#ffffff',
          cancel_button_border_color: '#13c2a2',
          cancel_button_text_color: '#0B715E',
        },
      };
    default:
      return {
        backgroundColor: metadata.backgroundGradient.start,
        color: metadata.backgroundColor.end,
      };
  }
};