export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const INCREMENT_UNREAD = 'INCREMENT_UNREAD';
export const RESET_UNREAD = 'RESET_UNREAD';
export const MARK_AS_READ = 'MARK_AS_READ';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';